// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using ContactsList.API;
using ContactsList.API.Models;
using Microsoft.Rest;

namespace ContactsList.API
{
    public static partial class ContactsExtensions
    {
        /// <param name='operations'>
        /// Reference to the ContactsList.API.IContacts.
        /// </param>
        public static IList<Contact> Get(this IContacts operations)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IContacts)s).GetAsync();
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the ContactsList.API.IContacts.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<IList<Contact>> GetAsync(this IContacts operations, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<System.Collections.Generic.IList<ContactsList.API.Models.Contact>> result = await operations.GetWithOperationResponseAsync(cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
