// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using ContactsList.API.Models;
using Newtonsoft.Json.Linq;

namespace ContactsList.API.Models
{
    public static partial class ContactCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<Contact> DeserializeJson(JToken inputObject)
        {
            IList<Contact> deserializedObject = new List<Contact>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                Contact contact = new Contact();
                contact.DeserializeJson(iListValue);
                deserializedObject.Add(contact);
            }
            return deserializedObject;
        }
    }
}
